version: '2'

services:
  anmeldeystem-backend:
    build: .
    image: anmeldesystem-backend
    restart: always
    container_name: anmeldesystem-backend
    env_file:
      - ./.env
    ports:
      - 3000:3000